### ISSUE TITLE
AWQ cuda OOM errors

### ISSUE THREAD

**Issue by HarmonyTechLabs** [mit-han-lab/llm-awq#106]
Hello! I have been trying to use AWQ on several different platforms but no matter which platform I use, I get an out of memory error when using any RoPE factors outside of null in the config.json file. If I stick with the standard 4096 context it will run, but I have the capability to scale up to 12,288. I can accomplish this with GPTQ.

This is being done with multiple 70b models on two 3090 cards. Here is the output from the aphrodite project using AWQ:

```bash
2023-10-27 21:53:44,428 INFO worker.py:1636 -- Started a local Ray instance.
INFO 10-27 21:53:48 aphrodite_engine.py:72] Initializing an LLM engine with config: model='/var/lib/docker-mounts/ssdStorage/textgen-models/TheBloke_Euryale-1.3-L2-70B-AWQ/', tokenizer='/var/lib/docker-mounts/ssdStorage/textgen-models/TheBloke_Euryale-1.3-L2-70B-AWQ/', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=awq, seed=0)
Traceback (most recent call last):
  File "/home/ai-tools/aphrodite-engine/conda/envs/linux/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ai-tools/aphrodite-engine/conda/envs/linux/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ai-tools/aphrodite-engine/aphrodite/endpoints/api_server_kobold.py", line 251, in <module>
    engine = AsyncAphrodite.from_engine_args(engine_args)
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 484, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 268, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/async_aphrodite.py", line 304, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 105, in __init__
    self._init_workers_ray(placement_group)
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 178, in _init_workers_ray
    self._run_workers(
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/aphrodite_engine.py", line 695, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/home/ai-tools/aphrodite-engine/conda/envs/linux/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ai-tools/aphrodite-engine/conda/envs/linux/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ai-tools/aphrodite-engine/conda/envs/linux/lib/python3.10/site-packages/ray/_private/worker.py", line 2540, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorker.execute_method() (pid=111936, ip=192.168.1.100, actor_id=8f4b9a5507b2fb69a95f1eb801000000, repr=<aphrodite.engine.ray_tools.RayWorker object at 0x7f2371f7aa10>)
  File "/home/ai-tools/aphrodite-engine/aphrodite/engine/ray_tools.py", line 33, in execute_method
    return executor(*args, **kwargs)
  File "/home/ai-tools/aphrodite-engine/aphrodite/task_handler/worker.py", line 65, in init_model
    _init_distributed_environment(self.parallel_config, self.rank,
  File "/home/ai-tools/aphrodite-engine/aphrodite/task_handler/worker.py", line 393, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

TGI results are the same but without the ray errors.

**Comment by HarmonyTechLabs** [comment]
Here is the detailed ticket I logged with TGI: https://github.com/huggingface/text-generation-inference/issues/1067
