### ISSUE TITLE
ImportError: DLL load failed while importing awq_inference_engine

### ISSUE THREAD

**Issue by protector131090** [mit-han-lab/llm-awq#118]
2023-11-12 22:13:45 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "S:\oobabooga\text-generation-webui-main\modules\ui_model_menu.py", line 210, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "S:\oobabooga\text-generation-webui-main\modules\models.py", line 85, in load_model
    output = load_func_map[loader](model_name)
  File "S:\oobabooga\text-generation-webui-main\modules\models.py", line 299, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\models\base.py", line 12, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "S:\oobabooga\text-generation-webui-main\installer_files\env\lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: DLL load failed while importing awq_inference_engine: Не найден указанный модуль.

**Comment by SDSSSpai** [comment]
Та же проблема. На сколько понял проблема в версиях CUDA Старые рабатают а новая нет. Почитайте сдесь если интерестно. https://github.com/oobabooga/text-generation-webui/issues/4253
