### ISSUE TITLE
Dead repo?

### ISSUE THREAD

**Issue by guspuffygit** [mit-han-lab/llm-awq#140]
It looks like none of the instructions work, can anyone recommend an updated fork?

```
Traceback (most recent call last):
  File "/home/guspuffy/anaconda3/envs/awq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/guspuffy/anaconda3/envs/awq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/guspuffy/third-party/llm-awq/awq/entry.py", line 15, in <module>
    from awq.quantize.pre_quant import run_awq, apply_awq
  File "/home/guspuffy/third-party/llm-awq/awq/quantize/pre_quant.py", line 12, in <module>
    from .auto_scale import auto_scale_block, apply_scale
  File "/home/guspuffy/third-party/llm-awq/awq/quantize/auto_scale.py", line 10, in <module>
    from .qmodule import ScaledActivation
  File "/home/guspuffy/third-party/llm-awq/awq/quantize/qmodule.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ModuleNotFoundError: No module named 'awq_inference_engine'
```

**Comment by ys-2020** [comment]
Hi. You need to follow the readme and install awq_inference_engine with `python setup.py install` in `awq/kernels`.
