### ISSUE TITLE
KeyError: 'llava_llama'

### ISSUE THREAD

**Issue by huzicong** [mit-han-lab/llm-awq#159]
When I ran vila's demo, I ran into the bug below：
![image](https://github.com/mit-han-lab/llm-awq/assets/101184592/6ceea783-2b53-4af0-a77c-a71339bb4ad2)

**Comment by ocg2347** [comment]
I imagine you missed a step during VILA installation:
`https://github.com/Efficient-Large-Model/VILA`
Source: README/Installation @ https://github.com/Efficient-Large-Model/VILA

**Comment by huwade** [comment]
Hi, all

Thank you for the great work, but I am encountering the same problem here. I have followed the VILA installation guide:


`cp -rv ./llava/train/transformers_replace/* $site_pkg_path/transformers/`
`cp -rv ./llava/train/deepspeed_replace/* $site_pkg_path/deepspeed/`

```sh
'./llava/train/transformers_replace/modeling_utils.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/modeling_utils.py'
'./llava/train/transformers_replace/models/gemma/__init__.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/gemma/__init__.py'
'./llava/train/transformers_replace/models/gemma/configuration_gemma.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/gemma/configuration_gemma.py'
'./llava/train/transformers_replace/models/gemma/modeling_gemma.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/gemma/modeling_gemma.py'
'./llava/train/transformers_replace/models/llama/configuring_llama.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/llama/configuring_llama.py'
'./llava/train/transformers_replace/models/llama/modeling_llama.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py'
'./llava/train/transformers_replace/models/llama/tokenization_llama.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py'
'./llava/train/transformers_replace/models/mistral/__init__.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mistral/__init__.py'
'./llava/train/transformers_replace/models/mistral/configuration_mistral.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mistral/configuration_mistral.py'
'./llava/train/transformers_replace/models/mistral/modeling_mistral.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py'
'./llava/train/transformers_replace/models/mixtral/__init__.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mixtral/__init__.py'
'./llava/train/transformers_replace/models/mixtral/configuration_mixtral.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mixtral/configuration_mixtral.py'
'./llava/train/transformers_replace/models/mixtral/modeling_mixtral.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py'
'./llava/train/deepspeed_replace/runtime/zero/mics.py' -> '/opt/conda/envs/python=3.10/lib/python3.10/site-packages/deepspeed/runtime/zero/mics.py'
```

Then I ran the following command:
`(python=3.10) root@4e2d31ab773d:/project/llm-awq# python -m awq.entry --model_path models--Efficient-Large-Model--VILA1.5-40b/snapshots/742691c2792095f9c6fd899cbb9207b4cf2b88f4/ --w_bit 4 --q_group_size 128 --vila-15 --run_awq --dump_awq awq_cache/$MODEL-w4-g128.pt`

I am encountering the KeyError like below

```Output:
Quantization config: {'zero_point': True, 'q_group_size': 128}
* Building model models--Efficient-Large-Model--VILA1.5-40b/snapshots/742691c2792095f9c6fd899cbb9207b4cf2b88f4/
Traceback (most recent call last):
  File "/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/opt/conda/envs/python=3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
    raise KeyError(key)
KeyError: 'llava_llama'
```

**Comment by surfingnirvana** [comment]
Does that still work?

**Comment by ZhangJinghe-AI** [comment]
@huzicong Have you solved this problem？
