### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by InkyuPak** [mit-han-lab/llm-awq#192]
transformers==4.36.2

(awq1) clrobur@clrobur-WS-C621E-SAGE-Series:~/vila/llm-awq/tinychat$ python vlm_demo_new.py --model-path VILA1.5-13b-AWQ --quant-path VILA1.5-13b-AWQ/llm/vila-1.5-13b-w4-g128-awq-v2.pt  --image-file image/image.png
Traceback (most recent call last):
  File "/home/clrobur/vila/llm-awq/tinychat/vlm_demo_new.py", line 238, in <module>
    main(args)
  File "/home/clrobur/vila/llm-awq/tinychat/vlm_demo_new.py", line 54, in main
    tokenizer = AutoTokenizer.from_pretrained(os.path.join(args.model_path, "llm"), use_fast=False)
  File "/home/clrobur/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 787, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/clrobur/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2028, in from_pretrained
    return cls._from_pretrained(
  File "/home/clrobur/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2260, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/clrobur/.local/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/home/clrobur/.local/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 209, in get_spm_processor
    model = model_pb2.ModelProto.FromString(sp_model)
google.protobuf.message.DecodeError: Error parsing message

**Comment by rukshankr** [comment]
@InkyuPak did you figure this out? I'm also stuck here
