### ISSUE TITLE
Guidance on CUDA driver and runtime versions

### ISSUE THREAD

**Issue by abhinavkulkarni** [mit-han-lab/llm-awq#25]
Hi,

I have two different setups where I wanted to run AWQ - I managed to run it successfully on one, but not on the other. 

The setup where I was able to run AWQ successfully has the following:

```bash
$ nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0
530.30.02

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

Whereas the unsuccessful setup has the following:

```bash
$ nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0
470.161.03

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

The second environment is a Kaggle notebook and the traceback is as follows:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/kaggle/working/llm-awq/awq/entry.py", line 9, in <module>
    from awq.quantize.pre_quant import run_awq, apply_awq
  File "/kaggle/working/llm-awq/awq/quantize/pre_quant.py", line 12, in <module>
    from .auto_scale import auto_scale_block, apply_scale
  File "/kaggle/working/llm-awq/awq/quantize/auto_scale.py", line 8, in <module>
    from .qmodule import ScaledActivation
  File "/kaggle/working/llm-awq/awq/quantize/qmodule.py", line 4, in <module>
    import f16s4_gemm  # with CUDA kernels
ModuleNotFoundError: No module named 'f16s4_gemm'
```

Thanks!

**Comment by abhinavkulkarni** [comment]
Thanks, I was able to figure out that CUDA architecture `sm_80` and above is needed to build the CUDA extension. That would translate to Ampere and onwards.
