### ISSUE TITLE
ModuleNotFoundError: No module named 'awq_inference_engine'

### ISSUE THREAD

**Issue by Hukongtao** [mit-han-lab/llm-awq#49]
I installed it according to the documentation step by step:  
https://github.com/mit-han-lab/llm-awq#install

```bash
git clone https://github.com/mit-han-lab/llm-awq
cd llm-awq
pip3 install -e .
cd awq/kernels
python setup.py install
```
![image](https://github.com/mit-han-lab/llm-awq/assets/16505966/53f1a669-96b5-4479-bd95-8aa14c6cbc3e)

But I got an error,  
![image](https://github.com/mit-han-lab/llm-awq/assets/16505966/43a76a58-0323-4e08-8b92-4a55ac00da32)

**Comment by Hukongtao** [comment]
awesome!
![image](https://github.com/mit-han-lab/llm-awq/assets/16505966/ed816da9-3f46-45bd-bbac-3caab0b0eea8)
https://stackoverflow.com/questions/65710713/importerror-libc10-so-cannot-open-shared-object-file-no-such-file-or-director

**Comment by rdaigle007** [comment]
I also get this error when I try to run the cli after installing AWQ per instructions

```
(env-fastchat-awq)Russells-MBP:llm-awq $ python3 -m fastchat.serve.cli --model-path models/git-vicuna-7b-awq/ --awq-wbits 4 --awq-groupsize 128
Loading AWQ quantized model...
Error: Failed to import tinychat. No module named 'awq_inference_engine'
Please double check if you have successfully installed AWQ
See https://github.com/lm-sys/FastChat/blob/main/docs/awq.md
```

Does FastChat only work if one has Nvidia GPU?  I do not.  My understanding is CUDA is only for Nvidia, which is why I was assuming the following error occured for me while installing:

```
(env-fastchat-awq)Russells-MBP:llm-awq $ cd awq/kernels/
(env-fastchat-awq)Russells-MBP:kernels $ python setup.py install
Traceback (most recent call last):
  File "/Volumes/ExtremePro/fastchat-awq/FastChat/repositories/llm-awq/awq/kernels/setup.py", line 35, in <module>
    CUDAExtension(
  File "/Volumes/ExtremePro/fastchat-awq/env-fastchat-awq/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
    library_dirs += library_paths(cuda=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtremePro/fastchat-awq/env-fastchat-awq/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/ExtremePro/fastchat-awq/env-fastchat-awq/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
(env-fastchat-awq)Russells-MBP:kernels $
(env-fastchat-awq)Russells-MBP:fastchat-awq $

```

**Comment by UIHCRITT** [comment]
> which is why I was assuming the following error occured for me while installing:

I also have this question

**Comment by Stark-zheng** [comment]
> I copied the .so file to the current directory and tried again: ![image](https://private-user-images.githubusercontent.com/16505966/256501942-238b4268-97b6-49ca-968b-e86702c6fed7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDQ4NzIsIm5iZiI6MTcxMjY0NDU3MiwicGF0aCI6Ii8xNjUwNTk2Ni8yNTY1MDE5NDItMjM4YjQyNjgtOTdiNi00OWNhLTk2OGItZTg2NzAyYzZmZWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZTk4NzcxN2YzYWMxNWZmZDg2MzYyZWEzMmE4MTViMWQwZjI1ZmVlYWIzODEwYzJiNjY5ZWQzMjYxNmE5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.npn6cccPm2Wf0crGvfTNfyYDRRHm4HUqfTqZ_OMOZtQ)

Where did you get this file?

**Comment by UIHCRITT** [comment]
> > > which is why I was assuming the following error occured for me while installing:
> > 
> > 
> > I also have this question
> 
> I met this error too, how did you solve it?Thanks!

I gave up, autoawq is more convenient,https://github.com/casper-hansen/AutoAWQ

**Comment by Yan0613** [comment]
> > > > which is why I was assuming the following error occured for me while installing:
> > > 
> > > 
> > > I also have this question
> > 
> > 
> > I met this error too, how did you solve it?Thanks!
> 
> I gave up, autoawq is more convenient,https://github.com/casper-hansen/AutoAWQ

OK, thanks!
