### ISSUE TITLE
Error Occurs When Quantizing LLaMA2-70B

### ISSUE THREAD

**Issue by Untitled47** [mit-han-lab/llm-awq#53]
I really appreciate authors' fantastic work done here.

When I tried to apply awq on LLaMA2-70B, however, the error below poped out:

```
Running AWQ...:   0%|                                                                                                                               | 0/80 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/vma/.conda/envs/awq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vma/.conda/envs/awq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/proj/Projects/FastChat/repo/llm-awq/awq/entry.py", line 214, in <module>
    main()
  File "/proj/Projects/FastChat/repo/llm-awq/awq/entry.py", line 189, in main
    model, enc = build_model_and_enc(args.model_path)
  File "/proj/Projects/FastChat/repo/llm-awq/awq/entry.py", line 122, in build_model_and_enc
    awq_results = run_awq(
  File "/home/vma/.conda/envs/awq/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/proj/Projects/FastChat/repo/llm-awq/awq/quantize/pre_quant.py", line 149, in run_awq
    apply_scale(layers[i], scales_list, input_feat_dict=input_feat)
  File "/proj/Projects/FastChat/repo/llm-awq/awq/quantize/auto_scale.py", line 355, in apply_scale
    scale_fc_fc(prev_op, layers[0], scales)
  File "/home/vma/.conda/envs/awq/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/proj/Projects/FastChat/repo/llm-awq/awq/quantize/auto_scale.py", line 68, in scale_fc_fc
    fc1.weight[-scales.size(0):].div_(scales.view(-1, 1))
RuntimeError: The size of tensor a (1024) must match the size of tensor b (8192) at non-singleton dimension 0
```
This error is really unexpected, since awq works fine on LLaMA2-7B and LLaMA2-13B.

I wonder if anyone could give me some hint about solving this problem.

Thanks in advance.

**Comment by tonylins** [comment]
Hi, thanks for your interests in our work. The LLaMA2-70B model uses Multi-Query Attention instead of Multi-Head Attention, which has not been supported yet. We are working on this at this moment. Please stay tuned.

**Comment by 0x1997** [comment]
Any updates?

**Comment by tonylins** [comment]
Thanks for following up. We should have a preliminary implementation in these two days.
